@extends('layouts.main')

@section('container')
<h3 class="text-indigo-600 fw-bold pt-5 px-5 mx-3 mb-3">Kelas <span class="text-indigo-900">{{ $class->namaCourse }}</span></h3>
<div class="class-details d-flex flex-column text-indigo-900 px-5 mx-3">
  <p>Mentored by {{ $kelas->mentor->namaMentor }} | <a class="text-indigo-600" href="/categories/{{ $kelas->category->slugCategory }}" style="text-decoration: none;">{{ $class->category->namaCategory }}</a></p>
  <p>{{ $kelas->lamaVideo }} Belajar dengan <span> {{ $kelas->jumlahVideo }}</span></p>
  <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta repellendus consequatur debitis, in cumque dignissimos pariatur at corporis non adipisci quo unde eum voluptate cum nam, deleniti iure magnam placeat quod earum facilis! Possimus reprehenderit aliquid, modi facilis doloremque quibusdam at consequuntur maxime pariatur obcaecati incidunt porro in sit laborum mollitia ea totam accusamus aut. Nihil facere earum, dignissimos quasi eos exercitationem possimus itaque laborum aspernatur architecto aperiam numquam voluptate et dolorum soluta laudantium! Laboriosam eaque amet expedita perspiciatis dolor placeat minima deleniti quas quia nisi reprehenderit, temporibus, a nesciunt quae omnis facere laudantium eius! Quas temporibus a aperiam quae magni autem accusantium ea suscipit ex unde. Maxime eius eaque quas labore quia porro temporibus ipsam tempore, sapiente ullam eveniet dicta quibusdam saepe? Praesentium, earum expedita autem quaerat totam maxime! Ea, delectus sed repudiandae veniam quia asperiores ex? Et rem nisi maiores inventore soluta consequatur, quisquam, eligendi placeat culpa expedita, accusantium nihil facilis harum illo quibusdam dolor. Dolorum non fugit enim maxime excepturi mollitia consectetur doloribus quibusdam quod voluptatibus molestias corrupti neque atque commodi praesentium veniam aut ab sed cum, tempore fuga maiores repudiandae! Itaque corporis ad ex necessitatibus animi dignissimos eos inventore facere! Facilis sunt ducimus quod porro magnam.</p>
  <p>{{ $kelas->hargaCourse }}</p>
  <a href="/classes" class="text-indigo-600" style="text-decoration: none;">Back to Classes</a>
</div>
@endsection